/*
 lazysizes - v5.3.2 */
'use strict';window.Element&&!Element.prototype.closest&&(Element.prototype.closest=function(a){a=(this.document||this.ownerDocument).querySelectorAll(a);var e=this,d;do for(d=a.length;0<=--d&&a.item(d)!==e;);while(0>d&&(e=e.parentElement));return e});
window.Element&&!Element.prototype.matches&&(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||Element.prototype.webkitMatchesSelector||function(a){a=(this.document||this.ownerDocument).querySelectorAll(a);for(var e=a.length;0<=--e&&a.item(e)!==this;);return-1<e});
Object.assign||(Object.assign=function(a,e){if(null===a)throw new TypeError("Cannot convert undefined or null to object");for(var d=Object(a),c=1;c<arguments.length;c++){var k=arguments[c];if(null!==k)for(var g in k)Object.prototype.hasOwnProperty.call(k,g)&&(d[g]=k[g])}return d});
(function(a){a.forEach(function(a){a.hasOwnProperty("remove")||Object.defineProperty(a,"remove",{configurable:!0,enumerable:!0,writable:!0,value:function(){this.parentNode.removeChild(this)}})})})([Element.prototype,CharacterData.prototype,DocumentType.prototype]);
(function(){function a(b){b=b.dataset;var a=[],c="image";c=c.charAt(0).toUpperCase()+c.slice(1);c=["is","hook"+c];for(var g in b)if(b.hasOwnProperty(g)){var k=b[g];0===g.indexOf("cmp")&&(g=g.slice(3),g=g.charAt(0).toLowerCase()+g.substring(1),-1===c.indexOf(g)&&(a[g]=k))}return a}function e(a){function e(b){b.element.removeAttribute("data-cmp-is");var a=b.options;f._properties={};for(var d in g)if(g.hasOwnProperty(d)){var e=g[d];f._properties[d]=a&&null!=a[d]?e&&"function"===typeof e.transform?e.transform(a[d]):
a[d]:g[d]["default"]}b=b.element;f._elements={};f._elements.self=b;b=f._elements.self.querySelectorAll("[data-cmp-hook-image]");for(a=0;a<b.length;a++)d=b[a],e="image",e=e.charAt(0).toUpperCase()+e.slice(1),f._elements[d.dataset["cmpHook"+e]]=d;if(f._elements.noscript){f._elements.container=f._elements.link?f._elements.link:f._elements.self;b=f._elements.noscript.textContent.trim();b=b.replace(/&(amp;)*lt;/g,"\x3c");b=b.replace(/&(amp;)*gt;/g,"\x3e");b=(new DOMParser).parseFromString(b,"text/html");
a=b.querySelector(c.image);a.removeAttribute("src");f._elements.container.insertBefore(a,f._elements.noscript);(b=b.querySelector(c.map))&&f._elements.container.insertBefore(b,f._elements.noscript);f._elements.noscript.parentNode.removeChild(f._elements.noscript);f._elements.container.matches(c.image)?f._elements.image=f._elements.container:f._elements.image=f._elements.container.querySelector(c.image);f._elements.map=f._elements.container.querySelector(c.map);f._elements.areas=f._elements.container.querySelectorAll(c.area);
if(f._properties.lazy){b=f._elements.image.getAttribute("width");a=f._elements.image.getAttribute("height");if(b&&a){d=k.style;d["padding-bottom"]=a/b*100+"%";for(var m in d)d.hasOwnProperty(m)&&(f._elements.image.style[m]=d[m])}f._elements.image.setAttribute("src","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");f._elements.image.classList.add(k.cssClass);f._lazyLoaderShowing=!0}f._elements.map&&f._elements.image.addEventListener("load",h);window.addEventListener("scroll",
f.update);window.addEventListener("resize",t);window.addEventListener("update",f.update);f._elements.image.addEventListener("cmp-image-redraw",f.update);f.update()}}function d(){var a=f._properties.widths&&0<f._properties.widths.length;if(a){var h=f._elements.self;for(var g=h.clientWidth;0===g&&h.parentNode;)h=h.parentNode,g=h.clientWidth;h=g*b;g=f._properties.widths.length;for(var c=0;c<g-1&&f._properties.widths[c]<h;)c++;h="."+f._properties.widths[c].toString()}else h="";h=f._properties.src.replace("{.width}",
h);f._elements.image.getAttribute("src")!==h&&(f._elements.image.setAttribute("src",h),a||window.removeEventListener("scroll",f.update));f._lazyLoaderShowing&&f._elements.image.addEventListener("load",m)}function m(){f._elements.image.classList.remove(k.cssClass);for(var b in k.style)k.style.hasOwnProperty(b)&&(f._elements.image.style[b]="");f._elements.image.removeEventListener("load",m);f._lazyLoaderShowing=!1}function p(){if(f._elements.areas&&0<f._elements.areas.length)for(var b=0;b<f._elements.areas.length;b++){var h=
f._elements.image.width,a=f._elements.image.height;if(h&&a){var g=f._elements.areas[b].dataset.cmpRelcoords;if(g){g=g.split(",");for(var c=Array(g.length),d=0;d<c.length;d++)c[d]=0===d%2?parseInt(g[d]*h):parseInt(g[d]*a);f._elements.areas[b].coords=c}}}}function t(){f.update();p()}function h(){p()}var f=this;f.update=function(){if(f._properties.lazy){if(null===f._elements.container.offsetParent)var b=!1;else{b=window.pageYOffset;var h=b+document.documentElement.clientHeight,a=f._elements.container.getBoundingClientRect().top+
b;b=a+f._elements.container.clientHeight>=b-0&&a<=h+0}b&&d()}else d()};a&&a.element&&e(a)}function d(){for(var b=document.querySelectorAll(c.self),g=0;g<b.length;g++)new e({element:b[g],options:a(b[g])});b=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;g=document.querySelector("body");(new b(function(b){b.forEach(function(b){b=[].slice.call(b.addedNodes);0<b.length&&b.forEach(function(b){b.querySelectorAll&&[].slice.call(b.querySelectorAll(c.self)).forEach(function(b){new e({element:b,
options:a(b)})})})})})).observe(g,{subtree:!0,childList:!0,characterData:!0})}var c={self:'[data-cmp-is\x3d"image"]',image:'[data-cmp-hook-image\x3d"image"]',map:'[data-cmp-hook-image\x3d"map"]',area:'[data-cmp-hook-image\x3d"area"]'},k={cssClass:"cmp-image__image--is-loading",style:{height:0,"padding-bottom":""}},g={widths:{"default":[],transform:function(b){var a=[];b.split(",").forEach(function(b){b=parseFloat(b);isNaN(b)||a.push(b)});return a}},lazy:{"default":!1,transform:function(b){return!(null===
b||"undefined"===typeof b)}},src:{}},b=window.devicePixelRatio||1;"loading"!==document.readyState?d():document.addEventListener("DOMContentLoaded",d)})();
(function(){function a(a){a=a.dataset;var b=[],g="formText";g=g.charAt(0).toUpperCase()+g.slice(1);g=["is","hook"+g];for(var c in a)if(a.hasOwnProperty(c)){var d=a[c];0===c.indexOf("cmp")&&(c=c.slice(3),c=c.charAt(0).toLowerCase()+c.substring(1),-1===g.indexOf(c)&&(b[c]=d))}return b}function e(a){a.element&&a.element.removeAttribute("data-cmp-is");this._cacheElements(a.element);this._setupProperties(a.options);this._elements.input.addEventListener("invalid",this._onInvalid.bind(this));this._elements.input.addEventListener("input",
this._onInput.bind(this))}function d(){for(var g=document.querySelectorAll(c.self),b=0;b<g.length;b++)new e({element:g[b],options:a(g[b])});g=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;b=document.querySelector("body");(new g(function(b){b.forEach(function(b){b=[].slice.call(b.addedNodes);0<b.length&&b.forEach(function(b){b.querySelectorAll&&[].slice.call(b.querySelectorAll(c.self)).forEach(function(b){new e({element:b,options:a(b)})})})})})).observe(b,{subtree:!0,
childList:!0,characterData:!0})}var c={self:'[data-cmp-is\x3d"formText"]'},k={constraintMessage:{},requiredMessage:{}};e.prototype._onInvalid=function(a){a.target.setCustomValidity("");a.target.validity.typeMismatch?this._properties.constraintMessage&&a.target.setCustomValidity(this._properties.constraintMessage):a.target.validity.valueMissing&&this._properties.requiredMessage&&a.target.setCustomValidity(this._properties.requiredMessage)};e.prototype._onInput=function(a){a.target.setCustomValidity("")};
e.prototype._cacheElements=function(a){this._elements={};this._elements.self=a;a=this._elements.self.querySelectorAll("[data-cmp-hook-form-text]");for(var b=0;b<a.length;b++){var c=a[b],g="formText";g=g.charAt(0).toUpperCase()+g.slice(1);this._elements[c.dataset["cmpHook"+g]]=c}};e.prototype._setupProperties=function(a){this._properties={};for(var b in k)if(k.hasOwnProperty(b)){var c=k[b];this._properties[b]=a&&null!=a[b]?c&&"function"===typeof c.transform?c.transform(a[b]):a[b]:k[b]["default"]}};
"loading"!==document.readyState?d():document.addEventListener("DOMContentLoaded",d)})();
var msftModalManager=function(){function a(){function a(a){$(c).siblings().toArray().filter(function(b){return"SCRIPT"!==b.tagName&&"META"!==b.tagName}).forEach(function(b){a?b.setAttribute("aria-hidden",!0):b.removeAttribute("aria-hidden")})}$(".modal.renderModalOnPageLoad").on("onShow",function(c){a(!0)});$(".modal.renderModalOnPageLoad").on("onHide",function(c){a(!1)})}function e(){document.querySelectorAll(".renderModalOnPageLoad").forEach(function(a){c.appendChild(a)})}function d(){msGeoSelector.shouldRender().then(function(a){a?
(msGeoSelector.render(),msftEmailModal.shouldRender()&&$(document).on(msGeoSelector.CLOSED_EVENT,function(a){msftEmailModal.render()})):msftEmailModal.shouldRender()&&msftEmailModal.render()}).catch(function(){msftEmailModal.shouldRender()&&msftEmailModal.render()})}var c;$(document).ready(function(){c=document.querySelector("#modalsRenderedAfterPageLoad");a();e();d()})}();
!function(){var a=function(){function a(){return $.when(new Promise(function(b,a){!function n(){if(window.MsOnePlayer)return b();setTimeout(n,200)}()}))}var d="notFetched",c=!1,k=0,g=[];return{fetchScript:function(){return window.MsOnePlayer?$.when():"fetching"===d?a():((b=document.querySelectorAll(".aem-inline-video-component")).forEach(function(a){var d=new MutationObserver(function(a){!function(b,a){c||(b.forEach(function(b){b.addedNodes.forEach(function(b){b.classList&&b.classList.contains("c-video-player")&&
(k++,(b=b.closest(".video-modal"))&&new mwf.Modal({el:b}))})}),k===a&&($('link[href*\x3d"oneplayer.css"]').remove(),c=!0,g.forEach(function(b){b.disconnect()})))}(a,b.length)});d.observe(a,{childList:!0,subtree:!0});g.push(d)}),d="fetching",$.getScript("https://www.microsoft.com/videoplayer/js/oneplayer.js").then(function(){return d="fetched",a()}));var b}}}();window.msftOnePlayerVideo=a}();$(function(){$(".pause-onhide").on("onHide",function(){$(this).find("video").each(function(){this.pause()})})});
$(function(){$(".video-trigger").on("keypress",function(a){a=a.charCode||a.keyCode;32!==a&&13!==a||this.click()})});
window.addEventListener("load",function(){if(window.isFeatureEnabled("perf-tracker-1ds"))if(void 0===window.performance.toJSON)console.log("Performance telemetry was not found");else{var a=window.performance.toJSON();a=JSON.stringify(a);a=JSON.parse(a);var e=a.timing,d=a.navigation;const k=(a)=>{if(!document.cookie)return"";const b=document.cookie.split("; ").find((b)=>b.startsWith(a));return b?b.split("\x3d")[1]:""};try{let a;var c=window.performance.getEntriesByName("first-contentful-paint")[0].toJSON();
(new PerformanceObserver((b)=>{b=b.getEntries();b=b[b.length-1];a=b.renderTime||b.loadTime;c.lcp=a;window.telemetry.webAnalyticsPlugin.addTelemetryInitializer(function(b){b.data.timing=e;b.data.navigation=d;b.data.paint=c;b.data.bStore=k("bStore")})})).observe({type:"largest-contentful-paint",buffered:!0})}catch(g){}}});
!function(){function a(c){if(d[c])return d[c].exports;var k=d[c]={exports:{}};return e[c](k,k.exports,a),k.exports}var e={165:function(){$(function(){var a=$("#emailSup-modal");if(0!==a.length){a=a.find(".countryList");var d=a.attr("data-attribute-lang");if(d){d=d.split("-");d=d[d.length-1];var g=a.find("option[selected]");d!==g.attr("value")&&0!==a.find($("option[value\x3d".concat(d,"]"))).length&&(g.removeAttr("selected"),a.find($("option[value\x3d".concat(d,"]"))).attr("selected",""))}}})}},d=
{};a.n=function(c){var d=c&&c.__esModule?function(){return c.default}:function(){return c};return a.d(d,{a:d}),d};a.d=function(c,d){for(var g in d)a.o(d,g)&&!a.o(c,g)&&Object.defineProperty(c,g,{enumerable:!0,get:d[g]})};a.o=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)};a(165)}();
var msftEmailModal=function(){function a(){$(".countryList").change(function(){var a=$(".countryList").val(),c=$("#consentNotCanada"),e=$("#consentCanada");"CA"==a?(e.show(),c.hide(),e.attr("aria-hidden","false"),c.attr("aria-hidden","true")):(e.hide(),c.show(),e.attr("aria-hidden","true"),c.attr("aria-hidden","false"))})}var e=new Date;return{shouldRender:function(){if(!document.querySelector("#emailSignupForm"))return!1;var a=localStorage.lastEmailSupPop?new Date(localStorage.lastEmailSupPop):e;
a.setMonth(a.getMonth()+1);return a<=e},render:function(){localStorage.lastEmailSupPop=e;a();var d=document.querySelector("#emailSup-modal");(new mwf.FormValidation({el:document.querySelector("#emailSignupForm"),preventFormSubmission:!0})).el.addEventListener("onValid",function(a){$(".emailSup-swapContent").toggle();$("#emailSup-modal").focus();a=$(d).data("emailsupSelectorEndpoint");var c={email:$(".userEmail").val(),country:$(".countryList").val(),culture:navigator.language};$.post(a,c).fail(function(b,
a,c){localStorage.removeItem("lastEmailSupPop")})});var c={};mwf.version?c.el=d:c.modal=d;(new mwf.Modal(c)).show()}}}();
$(document).ready(function(){var a=$(".modal-header .emailSup-swapContent");if("undefined"!==typeof a&&a){a=a.first().find(":header");var e=document.querySelector(".emailSup-swapContent button.form-group");"undefined"!==typeof e&&e&&(e.dataset.biHn=a.text().trim(),e.dataset.biEhn=a.text().trim(),e.dataset.biCompnm="Modal: Default")}"CA"==$(".countryList").find("option[selected]").attr("value")?($("#consentNotCanada").css("display","none"),$("#consentCanada").css("display","block")):($("#consentCanada").css("display",
"none"),$("#consentNotCanada").css("display","block"))});
var msGeoSelector=function(){function a(){setTimeout(function(){$(document).trigger("ms.geoselector.closed")},3E3)}function e(){var b=["googlebot"],a=!1;if(null!=navigator){var c=navigator.userAgent;c&&c.includes(b[0])&&(a=!0)}return a}function d(h){try{if(!h||e())a();else{"undefined"==typeof n&&(n={language:h.language,region:h.country,localeCode:h.language+"-"+h.country});$(".preferred-redirect-confirm").html(h.marketRedirectConfirm).attr("lang",h.language).attr("hreflang",h.language).attr("dir",
h.dir);$(".preferred-redirect-reject").html(h.marketRedirectReject).attr("lang",h.language).attr("dir",h.dir);$(".preferred-redirect-text").html(h.marketRedirectText).attr("lang",h.language).attr("dir",h.dir);$(".preferred-redirect-heading").html(h.marketRedirectHeading).attr("lang",h.language).attr("dir",h.dir);$(".preferred-redirect-translate").html(h.marketRedirectTranslate).attr("lang",h.language).attr("dir",h.dir);$(".preferred-redirect-cancel").attr("aria-label",h.marketRedirectCancel).attr("lang",
h.language).attr("dir",h.dir);$(".redirect-text").each(function(){var b=c($(this).text(),h.primaryCountry);$(this).html(b)});$(".redirect-heading").each(function(){var b=c($(this).text(),h.secondaryCountry);$(this).html(b)});$(".redirect-confirm").each(function(){var b=c($(this).text(),h.primaryCountry);$(this).html(b);$(this).attr("data-bi-cN",b.trim());$(this).attr("data-bi-ecN",b.trim());$(this).attr("data-bi-hN",$(".preferred-redirect-heading").text().trim());$(this).attr("data-bi-ehN",$(".preferred-redirect-heading").text().trim())});
$(".redirect-reject").each(function(){var b=c($(this).text(),h.secondaryCountry);$(this).html(b);$(this).attr("data-bi-cN",b.trim());$(this).attr("data-bi-ecN",b.trim());$(this).attr("data-bi-hN",$(".preferred-redirect-heading").text().trim());$(this).attr("data-bi-ehN",$(".preferred-redirect-heading").text().trim())});q.language===n.language&&$(".same-language-hide").hide();var f=document.querySelector("#geo-selector-modal");f.addEventListener("onHide",function(b){a()});var d={};mwf.version?d.el=
f:d.modal=f;var k=new mwf.Modal(d);if(null!=h.marketRedirectConfirm&&""!=h.marketRedirectConfirm&&null!=h.marketRedirectReject&&""!=h.marketRedirectReject&&null!=h.marketRedirectText&&""!=h.marketRedirectText&&null!=h.marketRedirectHeading&&""!=h.marketRedirectHeading&&null!=h.marketRedirectTranslate&&""!=h.marketRedirectTranslate){var m=window.location.href.replace("/"+(p?p.localeCode:q.localeCode),"/"+(t?t.localeCode:n.localeCode));$.ajax({url:m,type:"HEAD",error:function(){a()},complete:function(b){switch(b.status){case 200:k.show();
break;default:a()}}})}else a();$(".redirect-reject").click({currentLocale:q,currentNonStandardLocale:p},b);g()}}catch(x){a()}}function c(b,a){return b.replace("{0}",a)}function k(b,a){b=b.replace(/\|/g,",");b=b.replace(/'/g,'"');b=$.parseJSON(b);return a?m(b.v):m(b.u)}function g(){var b=window.location.href.replace("/"+(p?p.localeCode:q.localeCode),"/"+(t?t.localeCode:n.localeCode));$(".redirect-confirm").attr("href",b)}function b(b){var a="'u':'"+b.data.currentLocale.localeCode+"'";b.data.currentNonStandardLocale&&
(a+="|'v':'"+b.data.currentNonStandardLocale.localeCode+"'");b="{'r':'1'|"+a+"}";a=location.hostname;a=a.substring(a.indexOf("."),a.length);$.cookie.raw=!0;$.cookie("mslocale",b,{expires:45,domain:a,path:"/"})}function m(b){if(b){var a=b.split("-");if(1<=a.length)return{language:a[0].toLowerCase(),region:a[a.length-1].toLowerCase(),localeCode:b.toLowerCase()}}}var q,n,l,p,t;return{shouldRender:function(){var b=$("#geo-selector-modal");if(!(b.length&&0<b.length))return Promise.resolve(!1);var a=$.cookie("mslocale");
if(void 0!==a){var c=b.data("currentLocaleCode"),d=b.data("currentNonStandardLocaleCode");b=k(a,!1);a=k(a,!0);c=m(c,!1);d=m(d,!0);a&&c&&c.region===a.region||b&&d&&b.region===d.region||a&&d&&a.region===d.region||b&&c&&!a&&!d&&b.region===c.region?b=!0:(n=b,t=a,q=c,p=d,b=!1);return Promise.resolve(!b)}a:{if((c=$(".geo-info").data())&&c.country_code)if(l=c.country_code.toLowerCase(),c=b.data("currentLocaleCode"),b=b.data("currentNonStandardLocaleCode"),q=m(c),(p=m(b))&&l){b=Promise.resolve(p.region!==
l);break a}else if(q&&l){b=Promise.resolve(q.region!==l);break a}b=Promise.resolve(!0)}return b},render:function(){var b=$("#geo-selector-modal").data("geoSelectorEndpoint"),c=$("#geo-selector-modal").data("geoSelectorCfpath");c="undefined"!==typeof n&&n?{preferredRegion:n.region,preferredLanguage:n.language,preferredNonStandardLocaleCode:t?t.localeCode:void 0,currentRegion:q.region,currentLanguage:q.language,currentNonStandardLocaleCode:p?p.localeCode:void 0,cfPath:c,supportNonstandardLocales:window.isFeatureEnabled("support-unsupported-locales")}:
{currentRegion:q.region,currentLanguage:q.language,preferredAkamaiRegion:l,currentNonStandardLocaleCode:p?p.localeCode:void 0,cfPath:c,supportNonstandardLocales:window.isFeatureEnabled("support-unsupported-locales")};$.get(b,c).done(function(b){d(b)}).fail(function(){a()})},CLOSED_EVENT:"ms.geoselector.closed"}}();
$(document).ready(function(){document.querySelectorAll("div.content-placement-item .link-group \x3e a").forEach(function(a){var e=a.closest(".content-placement-item");"undefined"!==typeof e&&e&&(a.dataset.biEhn=e.querySelector("h1, h2, h3, h4, h5, h6").textContent,a.dataset.biHn=e.querySelector("h1, h2, h3, h4, h5, h6").textContent,a.dataset.biCompname=e.getAttribute("data-content-placement-style"),e=e.querySelector("img").src,"undefined"!==typeof e&&e&&(a.dataset.biAssetid=e))})});
(function(){var a=$("#uhfSkipToMain"),e=$(".azure-skip-nav"),d="";a.length?d=(d=a.data("href"))&&d.replace("#","")||"mainContent":e.length&&(d=(d=e[0].getAttribute("href"))&&d.replace("#","")||"main");$(".microsoft-template-layout-container").attr("id",d)})();
!function(a){var e=function(a,c,e){var d,b;if(function(){var c,d={lazyClass:"lazyload",loadedClass:"lazyloaded",loadingClass:"lazyloading",preloadClass:"lazypreload",errorClass:"lazyerror",autosizesClass:"lazyautosizes",fastLoadedClass:"ls-is-cached",iframeLoadMode:0,srcAttr:"data-src",srcsetAttr:"data-srcset",sizesAttr:"data-sizes",minSize:40,customMedia:{},init:!0,expFactor:1.5,hFac:.8,loadMode:2,loadHidden:!0,ricTimeout:0,throttleDelay:125};b=a.lazySizesConfig||a.lazysizesConfig||{};for(c in d)c in
b||(b[c]=d[c])}(),!c||!c.getElementsByClassName)return{init:function(){},cfg:b,noSupport:!0};var k=c.documentElement,q=a.HTMLPictureElement,n=a.addEventListener.bind(a),l=a.setTimeout,p=a.requestAnimationFrame||l,t=a.requestIdleCallback,h=/^picture$/i,f=["load","error","lazyincluded","_lazyloaded"],w={},ca=Array.prototype.forEach,C=function(b,a){w[a]||(w[a]=new RegExp("(\\s|^)"+a+"(\\s|$)"));return w[a].test(b.getAttribute("class")||"")&&w[a]},x=function(b,a){C(b,a)||b.setAttribute("class",(b.getAttribute("class")||
"").trim()+" "+a)},Q=function(b,a){var c;(c=C(b,a))&&b.setAttribute("class",(b.getAttribute("class")||"").replace(c," "))},R=function(b,a,c){var d=c?"addEventListener":"removeEventListener";c&&R(b,a);f.forEach(function(c){b[d](c,a)})},E=function(b,a,e,f,g){var h=c.createEvent("Event");e||(e={});e.instance=d;h.initEvent(a,!f,!g);h.detail=e;b.dispatchEvent(h);return h},S=function(c,d){var e;!q&&(e=a.picturefill||b.pf)?(d&&d.src&&!c.getAttribute("srcset")&&c.setAttribute("srcset",d.src),e({reevaluate:!0,
elements:[c]})):d&&d.src&&(c.src=d.src)},L=function(a,c,d){for(d=d||a.offsetWidth;d<b.minSize&&c&&!a._lazysizesWidth;)d=c.offsetWidth,c=c.parentNode;return d},H=function(){var b,a,d=[],e=[],f=d,g=function(){var c=f;f=d.length?e:d;b=!0;for(a=!1;c.length;)c.shift()();b=!1},h=function(d,e){b&&!e?d.apply(this,arguments):(f.push(d),a||(a=!0,(c.hidden?l:p)(g)))};h._lsFlush=g;return h}(),M=function(b,a){return a?function(){H(b)}:function(){var a=this,c=arguments;H(function(){b.apply(a,c)})}},ea=function(a){var c,
d=0,f=b.throttleDelay,g=b.ricTimeout,h=function(){c=!1;d=e.now();a()},k=t&&49<g?function(){t(h,{timeout:g});g!==b.ricTimeout&&(g=b.ricTimeout)}:M(function(){l(h)},!0);return function(b){if(b=!0===b)g=33;if(!c){c=!0;var a=f-(e.now()-d);0>a&&(a=0);b||9>a?k():l(k,a)}}},V=function(b){var a,c,d=function(){a=null;b()},f=function(){var b=e.now()-c;99>b?l(f,99-b):(t||d)(d)};return function(){c=e.now();a||(a=l(f,99))}},P=function(){var f,g,m,q,D,U,t,F,G,I,J,w,B=/^img$/i,L=/^iframe$/i,P="onscroll"in a&&!/(gle|ing)bot/.test(navigator.userAgent),
N=0,v=0,A=-1,W=function(b){v--;if(!b||0>v||!b.target)v=0},X=function(b){null==w&&(w="hidden"==(getComputedStyle(c.body,null)||{}).visibility);return w||!("hidden"==(getComputedStyle(b.parentNode,null)||{}).visibility&&"hidden"==(getComputedStyle(b,null)||{}).visibility)},Y=function(){var a,e,h,n,m=d.elements;if((q=b.loadMode)&&8>v&&(a=m.length)){var l=0;for(A++;l<a;l++)if(m[l]&&!m[l]._lazyRace)if(!P||d.prematureUnveil&&d.prematureUnveil(m[l]))K(m[l]);else{(n=m[l].getAttribute("data-expand"))&&(h=
1*n)||(h=N);if(!p){var p=!b.expand||1>b.expand?500<k.clientHeight&&500<k.clientWidth?500:370:b.expand;d._defEx=p;var r=p*b.expFactor;var D=b.hFac;w=null;N<r&&1>v&&2<A&&2<q&&!c.hidden?(N=r,A=0):N=1<q&&1<A&&6>v?p:0}if(da!==h){U=innerWidth+h*D;t=innerHeight+h;var u=-1*h;var da=h}r=m[l].getBoundingClientRect();if((r=(J=r.bottom)>=u&&(F=r.top)<=t&&(I=r.right)>=u*D&&(G=r.left)<=U&&(J||I||G||F)&&(b.loadHidden||X(m[l])))&&!(r=g&&3>v&&!n&&(3>q||4>A))){var z=m[l];var y=h;r=z;z=X(z);F-=y;J+=y;G-=y;for(I+=y;z&&
(r=r.offsetParent)&&r!=c.body&&r!=k;)(z=0<((getComputedStyle(r,null)||{}).opacity||1))&&"visible"!=(getComputedStyle(r,null)||{}).overflow&&(y=r.getBoundingClientRect(),z=I>y.left&&G<y.right&&J>y.top-1&&F<y.bottom+1);r=z}if(r){K(m[l]);var x=!0;if(9<v)break}else!x&&g&&!e&&4>v&&4>A&&2<q&&(f[0]||b.preloadAfterLoad)&&(f[0]||!n&&(J||I||G||F||"auto"!=m[l].getAttribute(b.sizesAttr)))&&(e=f[0]||m[l])}e&&!x&&K(e)}},u=ea(Y),aa=function(a){var c=a.target;c._lazyCache?delete c._lazyCache:(W(a),x(c,b.loadedClass),
Q(c,b.loadingClass),R(c,Z),E(c,"lazyloaded"))},fa=M(aa),Z=function(b){fa({target:b.target})},ha=function(a,c){var d=a.getAttribute("data-load-mode")||b.iframeLoadMode;0==d?a.contentWindow.location.replace(c):1==d&&(a.src=c)},ia=function(a){var c,d=a.getAttribute(b.srcsetAttr);(c=b.customMedia[a.getAttribute("data-media")||a.getAttribute("media")])&&a.setAttribute("media",c);d&&a.setAttribute("srcset",d)},ja=M(function(a,c,d,e,f){var g,k;if(!(k=E(a,"lazybeforeunveil",c)).defaultPrevented){e&&(d?x(a,
b.autosizesClass):a.setAttribute("sizes",e));e=a.getAttribute(b.srcsetAttr);d=a.getAttribute(b.srcAttr);if(f)var n=(g=a.parentNode)&&h.test(g.nodeName||"");var p=c.firesLoad||"src"in a&&(e||d||n);k={target:a};x(a,b.loadingClass);p&&(clearTimeout(m),m=l(W,2500),R(a,Z,!0));n&&ca.call(g.getElementsByTagName("source"),ia);e?a.setAttribute("srcset",e):d&&!n&&(L.test(a.nodeName)?ha(a,d):a.src=d);f&&(e||n)&&S(a,{src:d})}a._lazyRace&&delete a._lazyRace;Q(a,b.lazyClass);H(function(){var c=a.complete&&1<a.naturalWidth;
if(!p||c)c&&x(a,b.fastLoadedClass),aa(k),a._lazyCache=!0,l(function(){"_lazyCache"in a&&delete a._lazyCache},9);"lazy"==a.loading&&v--},!0)}),K=function(a){if(!a._lazyRace){var c=B.test(a.nodeName),d=c&&(a.getAttribute(b.sizesAttr)||a.getAttribute("sizes")),e="auto"==d;if(!e&&g||!c||!a.getAttribute("src")&&!a.srcset||a.complete||C(a,b.errorClass)||!C(a,b.lazyClass)){var f=E(a,"lazyunveilread").detail;e&&T.updateElem(a,!0,a.offsetWidth);a._lazyRace=!0;v++;ja(a,f,e,d,c)}}},ka=V(function(){b.loadMode=
3;u()}),ba=function(){3==b.loadMode&&(b.loadMode=2);ka()},O=function(){g||(999>e.now()-D?l(O,999):(g=!0,b.loadMode=3,u(),n("scroll",ba,!0)))};return{_:function(){D=e.now();d.elements=c.getElementsByClassName(b.lazyClass);f=c.getElementsByClassName(b.lazyClass+" "+b.preloadClass);n("scroll",u,!0);n("resize",u,!0);n("pageshow",function(a){if(a.persisted){var d=c.querySelectorAll("."+b.loadingClass);d.length&&d.forEach&&p(function(){d.forEach(function(a){a.complete&&K(a)})})}});a.MutationObserver?(new MutationObserver(u)).observe(k,
{childList:!0,subtree:!0,attributes:!0}):(k.addEventListener("DOMNodeInserted",u,!0),k.addEventListener("DOMAttrModified",u,!0),setInterval(u,999));n("hashchange",u,!0);"focus mouseover click load transitionend animationend".split(" ").forEach(function(a){c.addEventListener(a,u,!0)});/d$|^c/.test(c.readyState)?O():(n("load",O),c.addEventListener("DOMContentLoaded",u),l(O,2E4));d.elements.length?(Y(),H._lsFlush()):u()},checkElems:u,unveil:K,_aLSL:ba}}(),T=function(){var a,d=M(function(a,b,c,d){var e;
a._lazysizesWidth=d;d+="px";a.setAttribute("sizes",d);if(h.test(b.nodeName||"")){b=b.getElementsByTagName("source");var f=0;for(e=b.length;f<e;f++)b[f].setAttribute("sizes",d)}c.detail.dataAttr||S(a,c.detail)}),e=function(a,b,c){var e=a.parentNode;e&&(c=L(a,e,c),b=E(a,"lazybeforesizes",{width:c,dataAttr:!!b}),b.defaultPrevented||(c=b.detail.width)&&c!==a._lazysizesWidth&&d(a,e,b,c))},f=V(function(){var b,c=a.length;if(c)for(b=0;b<c;b++)e(a[b])});return{_:function(){a=c.getElementsByClassName(b.autosizesClass);
n("resize",f)},checkElems:f,updateElem:e}}(),B=function(){!B.i&&c.getElementsByClassName&&(B.i=!0,T._(),P._())};return l(function(){b.init&&B()}),d={cfg:b,autoSizer:T,loader:P,init:B,uP:S,aC:x,rC:Q,hC:C,fire:E,gW:L,rAF:H}}(a,a.document,Date);a.lazySizes=e;"object"==typeof module&&module.exports&&(module.exports=e)}("undefined"!=typeof window?window:{});window.lazySizesConfig=window.lazySizesConfig||{};lazySizesConfig.loadMode=1;lazySizesConfig.preloadAfterLoad=!0;